name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.7.*
  - black
  - flake8
  - pyodbc==4.0.28
  - psycopg2==2.8.4
  - sqlalchemy==1.3.11
  - pandas 0.25.*
  - boto3 1.10.*
  - awscli 1.16.*
  - jupyterlab==1.2.4
  - fire
  - pyarrow 0.15.*
  - s3fs==0.4.0
  - openpyxl 3.0.*
  - gensim==3.8.1
  - mlflow 1.5.*
  - scikit-learn 0.22.*
  - nodejs 12.4.*
  - pytest 5.4.*
  - pip
  - pip:
    - lightgbm==2.3.0
    - shap==0.33.0
    - eliot==1.11.0
    - eliot-tree==18.1.1
    - mmh3==2.5.1
    - dill==0.3.1.1
    - hyperopt
    - nltk
    - gensim
    - negspacy==0.1.7
